# Generated by Django 5.2.7 on 2025-11-10 15:54

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parents", "__first__"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="student",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="student",
            name="student_class",
        ),
        migrations.AddField(
            model_name="student",
            name="admission_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="student",
            name="class_name",
            field=models.CharField(default="Class 1", max_length=50),
        ),
        migrations.AddField(
            model_name="student",
            name="contact_number",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="student",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="student",
            name="date_of_birth",
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="student",
            name="first_name",
            field=models.CharField(default="First", max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default="M",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="last_name",
            field=models.CharField(default="Last", max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="roll_number",
            field=models.CharField(default="0001", max_length=20),
        ),
        migrations.AddField(
            model_name="student",
            name="section",
            field=models.CharField(default="A", max_length=10),
        ),
        migrations.AddField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("graduated", "Graduated"),
                ],
                default="active",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="student_id",
            field=models.CharField(default="STU000", max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name="student",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="parents.parent",
            ),
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                        ],
                        default="present",
                        max_length=10,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "date")},
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marks_obtained", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "total_marks",
                    models.DecimalField(decimal_places=2, default=100, max_digits=5),
                ),
                (
                    "percentage",
                    models.DecimalField(decimal_places=2, editable=False, max_digits=5),
                ),
                ("grade", models.CharField(max_length=2)),
                ("exam_name", models.CharField(max_length=100)),
                ("exam_date", models.DateField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="students.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.subject",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "subject", "exam_name")},
            },
        ),
    ]
