# Generated by Django 5.2.7 on 2025-11-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_subject_remove_student_full_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="address",
            field=models.TextField(blank=True),
        ),
    ]
